name: test Go using version matrix

on:
  push:
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: ["1.20.x", "1.21.x"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - run: make go-all-tests

#      - name: Test Summary
#        uses: test-summary/action@v2
#        with:
#          paths: "junit-report.xml"
#        if: always()
